version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: simpul_app:latest
    env_file:
      - .env.production
    environment:
      RAILS_ENV: production
      REDIS_URL: ${REDIS_URL}
    ports:
      - "3000:80"
    depends_on:
      - redis
      - db
    command: ["./bin/thrust", "./bin/rails", "server"]

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
