default: &default
  dispatchers:
    - batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
